name: Deploy to badsearch.ml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Publish build artifacts to remote server
      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@191986574c0735ffad7ae1a297a414d6e6f95375
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_RSA }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          SOURCE: commercial-search/
          TARGET: ${{ secrets.DEPLOY_DIR }}
          ARGS: -azv --delete --omit-dir-times --no-perms --exclude '.htaccess' --exclude '*.log' --exclude 'run.sh' --exclude '*.db' --exclude '*.sock' --exclude '.env' --exclude '__pycache__'
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_RSA }}
          script: cd ${{ secrets.DEPLOY_DIR }} && conda activate badsearch && flask gen-sitemaps; sudo systemctl restart badsearch
